### ISSUE TITLE
Unable to deactivate license

### ISSUE THREAD

**Issue by NateWr** [easydigitaldownloads/shoppette#1]
I'm having trouble deactivating the license on Shoppette. The license is entered and the `active` text shows. When I click `Deactivate License` the page refreshes, but the license is still showing as `active`. There are no errors in my apache log and no console errors pop up when I click the button.

What's interesting is that the license is now showing as `active` on two sites:

`192.168.0.8/mindingkids/wp/`
`dev.mindingkids.co.uk`

I'm using v1.0.4 of Shoppette at both locations and tested with all plugins deactivated. But I haven't looked any deeper. Happy to take a look later but a little busy at the moment.

Thanks!

**Comment by SeanChDavis** [comment]
Sorry... not sure how I missed this. Looks like I've got [something similar](https://github.com/easydigitaldownloads/quota/issues/1) going on in Quota. I'll get it taken care of.

**Comment by SeanChDavis** [comment]
Gonna go ahead and update the entire updater.
