### ISSUE TITLE
PHP warning in customizer

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/shoppette#11]
Just activated theme, went to customizer and see these errors:

```
Warning: Creating default object from empty value in /.../edd.dev/wp-content/themes/shoppette/inc/customizer.php on line 288
Warning: Creating default object from empty value in /.../edd.dev/wp-content/themes/shoppette/inc/customizer.php on line 289
```

Probably related but when proceeding to create a menu in the customizer, all the types of content available for adding to the menu show nothing available.

**Comment by brashrebel** [comment]
Oh, this might actually be fixed in the latest version. My bad. 1.0.5 is the only version in Dropbox.

**Comment by mindctrl** [comment]
@brashrebel confirmed fixed?

**Comment by SeanChDavis** [comment]
@brashrebel Sorry for missing this and not updating Dropbox. Fixed already, though. https://github.com/easydigitaldownloads/shoppette/pull/4/files
