### ISSUE TITLE
Removing spans from legends in EDD causes UI change.

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/shoppette#15]
For easydigitaldownloads/easy-digital-downloads#3568

![selection_418](https://cloud.githubusercontent.com/assets/341412/15368422/b2088858-1cfb-11e6-8589-d811aa8e96d8.png)

![selection_419](https://cloud.githubusercontent.com/assets/341412/15368426/b4e8838e-1cfb-11e6-878e-f21db91eae02.png)

**Comment by SeanChDavis** [comment]
Fixed for all versions of EDD. Just needs to go out before EDD 2.6.

**Comment by pippinsplugins** [comment]
@SDavisMedia can we push pre 2.6? Could it support both markups?
